version: '3.9'
services:
  models-frame-resources:
    image: local/models-frame-resources
    # build: .
    # command: python3.7 /app/server.py
    environment:
      ENV_ID: dev
      CUDA_VISIBLE_DEVICES: 0
      TF_FORCE_GPU_ALLOW_GROWTH: false
      SERVICE_NAME: models-frame-resources
    ports:
      - 8540:8540
    # volumes:
    #   - .:/app/
    network_mode: bridge
    tty: true
    restart: always
    networks:
      - gratheon
networks:
  gratheon:
